-- Originally generated by nwg-displays.
-- Converted to Hyprland Lua syntax.

hl.config({
    monitor = {
        "Virtual-1,1920x1080@144.0,1920x0,1.0",
        "eDP-1,1920x1080@144.0,0x0,1.0",
        "HDMI-A-1,1920x1080@144.0,1920x0,1.0",
        "DP-1,1920x1080@144.0,0x0,1.0"
    }
})