-- Originally generated by nwg-displays.
-- Converted to standard Hyprland Lua syntax.

hl.monitor({
    output   = "Virtual-1",
    mode     = "1920x1080@144.0",
    position = "1920x0",
    scale    = "1.0"
})

hl.monitor({
    output   = "eDP-1",
    mode     = "1920x1080@144.0",
    position = "0x0",
    scale    = "1.0"
})

hl.monitor({
    output   = "HDMI-A-1",
    mode     = "1920x1080@144.0",
    position = "1920x0",
    scale    = "1.0"
})

hl.monitor({
    output   = "DP-1",
    mode     = "1920x1080@144.0",
    position = "0x0",
    scale    = "1.0"
})