#!/bin/sh

if command -v dbus-update-activation-environment >/dev/null 2>&1; then
    dbus-update-activation-environment --systemd WAYLAND_DISPLAY DISPLAY XAUTHORITY
fi

screensetup

exec dbus-run-session -- dwm