#!/bin/sh

# Lock screen script using i3lock-color
# Matches Sway configuration style

i3lock \
    --color 2d353b \
    --inside-color 3a454a \
    --insidever-color 5a524c \
    --insidewrong-color 543a3a \
    --ring-color 7a8478 \
    --ringver-color dbbc7f \
    --ringwrong-color e67e80 \
    --keyhl-color d699b6 \
    --bshl-color e69875 \
    --separator-color 2d353b \
    --verif-color d3c6aa \
    --wrong-color d3c6aa \
    --time-color d3c6aa \
    --date-color d3c6aa \
    --layout-color d3c6aa \
    --radius 100 \
    --ring-width 10 \
    --clock \
    --indicator \
    --time-str="%H:%M:%S" \
    --date-str="%A, %m %Y" \
    --verif-text="Verifying..." \
    --wrong-text="Wrong!" \
    --noinput-text="No Input" \
    --lock-text="Locking..." \
    --lockfailed-text="Lock Failed" \
    --fonts="JetBrainsMono Nerd Font Propo"
